package br.com.devedores.app;
import android.app.*;import android.content.*;import android.os.*;import android.view.*;import android.widget.*;import java.util.Collections;
public class AddClientActivity extends Activity{
 EditText name,cpf,rg,phone,address,notes; DataStore ds;
 public void onCreate(Bundle b){super.onCreate(b);ds=new DataStore(this);build();}
 void build(){LinearLayout p=Ui.col(this);LinearLayout top=Ui.row(this);Button back=Ui.btnDark(this,"‹ Voltar");back.setOnClickListener(v->finish());top.addView(back,new LinearLayout.LayoutParams(Ui.dp(this,82),Ui.dp(this,46)));LinearLayout tt=Ui.col(this);tt.setPadding(Ui.dp(this,10),0,0,0);tt.addView(Ui.title(this,"Novo cliente",24));tt.addView(Ui.label(this,"Crie a pasta e mantenha tudo organizado."));top.addView(tt,new LinearLayout.LayoutParams(0,Ui.dp(this,56),1));p.addView(top);Ui.gap(this,p,18);
   LinearLayout intro=Ui.softCard(this,Ui.GOLD);intro.addView(Ui.eyebrow(this,"PASTA DO CLIENTE"));intro.addView(Ui.text(this,"Depois de salvar, você poderá adicionar RG, CPF, comprovantes, contratos, fotos, empréstimos e anotações.",14));p.addView(intro);Ui.gap(this,p,14);
   name=Ui.field(this,"Nome completo *");cpf=Ui.field(this,"CPF");rg=Ui.field(this,"RG");phone=Ui.field(this,"Telefone / WhatsApp");address=Ui.field(this,"Endereço");notes=Ui.field(this,"Anotações iniciais");EditText[] es=new EditText[]{name,cpf,rg,phone,address,notes};String[] labs=new String[]{"Identificação","CPF","RG","Contato","Endereço","Observações"};for(int i=0;i<es.length;i++){p.addView(Ui.eyebrow(this,labs[i]));p.addView(es[i],new LinearLayout.LayoutParams(-1,i==5?Ui.dp(this,100):Ui.dp(this,56)));Ui.gap(this,p,10);}
   Button save=Ui.btn(this,"Criar pasta e salvar");save.setOnClickListener(v->{if(name.getText().toString().trim().isEmpty()){name.setError("Informe o nome");return;}Models.Client c=new Models.Client();c.name=name.getText().toString().trim();c.cpf=cpf.getText().toString().trim();c.rg=rg.getText().toString().trim();c.phone=phone.getText().toString().trim();c.address=address.getText().toString().trim();c.notes=notes.getText().toString();Collections.addAll(c.folders,"RG","CPF","Comprovante","Contrato","Fotos","Outros");ds.clients.add(c);ds.save();Toast.makeText(this,"Cliente salvo com sucesso",Toast.LENGTH_SHORT).show();Intent i=new Intent(this,ClientActivity.class);i.putExtra("id",c.id);startActivity(i);finish();});p.addView(save,new LinearLayout.LayoutParams(-1,Ui.dp(this,54)));setContentView(p);}
}
