package br.com.devedores.app;
import android.app.*;import android.os.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.util.*;
public class AddLoanActivity extends Activity{
 DataStore ds; Models.Client client; EditText title,principal,interest,installments,firstDay; Spinner freq; Calendar due=Calendar.getInstance();
 public void onCreate(Bundle b){super.onCreate(b);ds=new DataStore(this);client=ds.client(getIntent().getStringExtra("clientId"));LinearLayout p=Ui.col(this);TextView h=Ui.text(this,"Novo empréstimo • "+client.name,24);h.setTypeface(null,1);p.addView(h);title=Ui.field(this,"Título (ex.: Empréstimo setembro)");principal=Ui.field(this,"Valor emprestado (R$)");interest=Ui.field(this,"Juros (%)");installments=Ui.field(this,"Quantidade de parcelas");for(EditText e:new EditText[]{title,principal,interest,installments}){p.addView(e,new LinearLayout.LayoutParams(-1,Ui.dp(this,58)));Ui.gap(this,p,7);}TextView fh=Ui.text(this,"Periodicidade",16);p.addView(fh);freq=new Spinner(this);freq.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"Semanal","Quinzenal","Mensal"}));p.addView(freq,new LinearLayout.LayoutParams(-1,Ui.dp(this,55)));Ui.gap(this,p,7);firstDay=Ui.field(this,"Primeiro vencimento (toque para escolher)");firstDay.setFocusable(false);firstDay.setText(dateText(due.getTimeInMillis()));firstDay.setOnClickListener(v->pickDate());p.addView(firstDay,new LinearLayout.LayoutParams(-1,Ui.dp(this,58)));Ui.gap(this,p,10);Button save=Ui.btn(this,"Criar empréstimo e agendar");save.setOnClickListener(v->save());p.addView(save,new LinearLayout.LayoutParams(-1,Ui.dp(this,55)));setContentView(p);}
 String dateText(long x){return new SimpleDateFormat("dd/MM/yyyy",Locale.getDefault()).format(new Date(x));}
 void pickDate(){new DatePickerDialog(this,(v,y,m,d)->{due.set(y,m,d,10,0,0);firstDay.setText(dateText(due.getTimeInMillis()));},due.get(Calendar.YEAR),due.get(Calendar.MONTH),due.get(Calendar.DAY_OF_MONTH)).show();}
 void save(){try{double p=Double.parseDouble(principal.getText().toString().replace(',','.'));double ip=Double.parseDouble(interest.getText().toString().replace(',','.'));int n=Integer.parseInt(installments.getText().toString());if(p<=0||n<=0)throw new Exception();Models.Loan l=new Models.Loan();l.title=title.getText().toString().trim().isEmpty()?"Empréstimo":title.getText().toString().trim();l.principal=p;l.interestPercent=ip;l.interestValue=p*ip/100d;l.total=p+l.interestValue;l.installments=n;l.frequency=freq.getSelectedItem().toString();l.installmentAmount=l.total/n;l.firstDue=due.getTimeInMillis();client.loans.add(l);ds.save();AlarmScheduler.schedule(this,"loan",l.id,client.name+" • "+l.title+" • parcela 1",l.firstDue);Toast.makeText(this,String.format(Locale.getDefault(),"Total: R$ %.2f",l.total),Toast.LENGTH_LONG).show();finish();}catch(Exception e){Toast.makeText(this,"Preencha valor, juros e parcelas corretamente.",Toast.LENGTH_LONG).show();}}
}
