package br.com.devedores.app;
import android.app.*;import android.content.*;import android.net.Uri;import android.os.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.util.*;
public class ClientActivity extends Activity{
 DataStore ds;Models.Client c;LinearLayout root;
 public void onCreate(Bundle b){super.onCreate(b);ds=new DataStore(this);c=ds.client(getIntent().getStringExtra("id"));build();}
 void build(){root=Ui.col(this);setContentView(root);TextView t=Ui.text(this,c.name,27);t.setTypeface(null,1);root.addView(t);root.addView(Ui.text(this,"CPF: "+c.cpf+"\nTelefone: "+c.phone+"\nEndereço: "+c.address,14));LinearLayout a=new LinearLayout(this);Button loan=Ui.btn(this,"+ Empréstimo");loan.setOnClickListener(v->{Intent i=new Intent(this,AddLoanActivity.class);i.putExtra("clientId",c.id);startActivity(i);});Button doc=Ui.btn(this,"Adicionar documento");doc.setOnClickListener(v->pickDoc());Button edit=Ui.btn(this,"Editar cliente");edit.setOnClickListener(v->editClient());a.addView(loan,new LinearLayout.LayoutParams(0,52*Ui.dp(this,1),1));a.addView(doc,new LinearLayout.LayoutParams(0,52*Ui.dp(this,1),1));a.addView(edit,new LinearLayout.LayoutParams(0,52*Ui.dp(this,1),1));root.addView(a);Ui.gap(this,root,12);TextView nh=Ui.text(this,"Anotações",19);root.addView(nh);EditText note=Ui.field(this,"Anotação do cliente");note.setText(c.notes);root.addView(note,new LinearLayout.LayoutParams(-1,Ui.dp(this,100)));Button saveNote=Ui.btn(this,"Salvar anotação");saveNote.setOnClickListener(v->{c.notes=note.getText().toString();ds.save();Toast.makeText(this,"Salvo",Toast.LENGTH_SHORT).show();});root.addView(saveNote);Ui.gap(this,root,14);TextView dh=Ui.text(this,"Documentos",19);root.addView(dh);for(String u:c.docs){TextView dv=Ui.text(this,"📎 "+u,14);dv.setOnClickListener(v->{try{Intent i=new Intent(Intent.ACTION_VIEW,Uri.parse(u));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(i);}catch(Exception ex){Toast.makeText(this,"Não foi possível abrir o documento",Toast.LENGTH_SHORT).show();}});root.addView(dv);}Ui.gap(this,root,14);TextView lh=Ui.text(this,"Empréstimos",19);root.addView(lh);for(Models.Loan l:c.loans){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);TextView z=Ui.text(this,l.title+"\nTotal: R$ "+String.format(Locale.getDefault(),"%.2f",l.total)+"  •  Restante: R$ "+String.format(Locale.getDefault(),"%.2f",l.balance()),16);z.setOnClickListener(v->{Intent i=new Intent(this,LoanActivity.class);i.putExtra("clientId",c.id);i.putExtra("loanId",l.id);startActivity(i);});row.addView(z);root.addView(row,new LinearLayout.LayoutParams(-1,Ui.dp(this,86)));}}
 void editClient(){LinearLayout p=Ui.col(this);EditText n=Ui.field(this,"Nome");n.setText(c.name);EditText ph=Ui.field(this,"Telefone");ph.setText(c.phone);EditText ad=Ui.field(this,"Endereço");ad.setText(c.address);EditText cp=Ui.field(this,"CPF");cp.setText(c.cpf);p.addView(n);p.addView(ph);p.addView(ad);p.addView(cp);new AlertDialog.Builder(this).setTitle("Editar cliente").setView(p).setPositiveButton("Salvar",(d,w)->{c.name=n.getText().toString();c.phone=ph.getText().toString();c.address=ad.getText().toString();c.cpf=cp.getText().toString();ds.save();build();}).setNegativeButton("Cancelar",null).show();}
 void pickDoc(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,44);}
 protected void onActivityResult(int r,int res,Intent d){super.onActivityResult(r,res,d);if(r==44&&res==RESULT_OK&&d!=null&&d.getData()!=null){Uri u=d.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}c.docs.add(u.toString());ds.save();build();}}
 @Override protected void onResume(){super.onResume();if(ds!=null){ds.load();c=ds.client(getIntent().getStringExtra("id"));if(c!=null){root=null;build();}}}
}
