package br.com.devedores.app;
import android.app.*;import android.content.*;import android.os.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.util.*;
public class LoanActivity extends Activity{
 DataStore ds;Models.Client client;Models.Loan loan;LinearLayout root;long nextDue=0;int nextIndex=-1;
 public void onCreate(Bundle b){super.onCreate(b);ds=new DataStore(this);client=ds.client(getIntent().getStringExtra("clientId"));loan=ds.loan(getIntent().getStringExtra("loanId"));build();}
 void build(){root=Ui.col(this);setContentView(root);TextView h=Ui.text(this,loan.title,25);h.setTypeface(null,1);root.addView(h);root.addView(Ui.text(this,String.format(Locale.getDefault(),"Emprestado: R$ %.2f\nJuros: R$ %.2f (%.2f%%)\nTotal da dívida: R$ %.2f\nPago: R$ %.2f\nRestante: R$ %.2f\n\n%d parcelas • %s • R$ %.2f cada",loan.principal,loan.interestValue,loan.interestPercent,loan.total,loan.paid(),loan.balance(),loan.installments,loan.frequency,loan.installmentAmount),16));Ui.gap(this,root,10);for(int i=0;i<loan.installments;i++){double pg=loan.paidForInstallment(i);long due=loan.dueAt(i);boolean paid=loan.installmentPaid(i);boolean late=!paid&&due<System.currentTimeMillis();if(!paid&&nextIndex<0){nextIndex=i;nextDue=due;}String st=paid?"✅ Paga":late?"🔴 Atrasada":"🟡 Pendente";TextView v=Ui.text(this,String.format(Locale.getDefault(),"Parcela %d • %s\nVencimento: %s\nPago nesta parcela: R$ %.2f / R$ %.2f",i+1,st,new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm",Locale.getDefault()).format(new Date(due)),pg,loan.installmentAmount),15);root.addView(v);Ui.gap(this,root,4);}LinearLayout a=new LinearLayout(this);Button pay=Ui.btn(this,"Registrar pagamento");pay.setOnClickListener(v->pay());Button res=Ui.btn(this,"Reagendar próxima");res.setOnClickListener(v->reschedule());a.addView(pay,new LinearLayout.LayoutParams(0,Ui.dp(this,52),1));a.addView(res,new LinearLayout.LayoutParams(0,Ui.dp(this,52),1));root.addView(a);}
 void pay(){if(loan.balance()<=0){Toast.makeText(this,"Empréstimo quitado",Toast.LENGTH_SHORT).show();return;}EditText e=Ui.field(this,"Valor pago (R$)");new AlertDialog.Builder(this).setTitle("Registrar pagamento").setView(e).setPositiveButton("Confirmar",(d,w)->{try{double a=Double.parseDouble(e.getText().toString().replace(',','.'));if(a<=0)throw new Exception();Models.Payment p=new Models.Payment();p.amount=Math.min(a,loan.balance());p.date=System.currentTimeMillis();loan.payments.add(p);ds.save();AlarmScheduler.rescheduleAll(this);build();Toast.makeText(this,"Pagamento salvo",Toast.LENGTH_SHORT).show();}catch(Exception x){Toast.makeText(this,"Informe um valor válido.",Toast.LENGTH_SHORT).show();}}).setNegativeButton("Cancelar",null).show();}
 void reschedule(){if(nextIndex<0){Toast.makeText(this,"Não há parcela pendente.",Toast.LENGTH_SHORT).show();return;}Calendar c=Calendar.getInstance();c.setTimeInMillis(nextDue);new DatePickerDialog(this,(v,y,m,d)->{Calendar x=Calendar.getInstance();x.set(y,m,d);new TimePickerDialog(this,(tv,h,min)->{x.set(Calendar.HOUR_OF_DAY,h);x.set(Calendar.MINUTE,min);x.set(Calendar.SECOND,0);long delta=x.getTimeInMillis()-nextDue;loan.firstDue+=delta;ds.save();AlarmScheduler.rescheduleAll(this);build();},c.get(Calendar.HOUR_OF_DAY),c.get(Calendar.MINUTE),true).show();},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show();}
 @Override protected void onResume(){super.onResume();if(ds!=null){ds.load();client=ds.client(getIntent().getStringExtra("clientId"));loan=ds.loan(getIntent().getStringExtra("loanId"));if(loan!=null)build();}}
}
