package br.com.devedores.app;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.os.*;import android.view.*;import android.widget.*;import java.text.*;import java.util.*;
public class MainActivity extends Activity{
 DataStore ds; LinearLayout root; TextView summary; int gold=Color.rgb(244,197,66); 
 @Override public void onCreate(Bundle b){super.onCreate(b);ds=new DataStore(this);notifyPermission();build();if(!AlarmScheduler.canExact(this)) new AlertDialog.Builder(this).setTitle("Ativar alarmes").setMessage("Para tocar notificações mesmo com o app fechado, permita 'Alarmes e lembretes' para o Devedores.").setPositiveButton("Abrir configurações",(d,w)->AlarmScheduler.openExactSettings(this)).setNegativeButton("Depois",null).show();}
 void notifyPermission(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},77);}
 TextView title(String s){TextView t=Ui.text(this,s,24);t.setTypeface(null,1);t.setTextColor(Color.WHITE);return t;}
 void build(){root=Ui.col(this);ScrollView sc=new ScrollView(this);sc.setFillViewport(true);sc.addView(root);setContentView(sc); LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.setOrientation(LinearLayout.HORIZONTAL);top.addView(title("Devedores"),new LinearLayout.LayoutParams(0,Ui.dp(this,60),1));Button add=Ui.btn(this,"+ Cliente");add.setOnClickListener(v->startActivity(new Intent(this,AddClientActivity.class)));top.addView(add,new LinearLayout.LayoutParams(Ui.dp(this,115),Ui.dp(this,50)));root.addView(top);summary=Ui.text(this,"",14);root.addView(summary);Ui.gap(this,root,8);LinearLayout actions=new LinearLayout(this);Button cal=Ui.btn(this,"Calendário");cal.setOnClickListener(v->startActivity(new Intent(this,CalendarActivity.class)));Button rem=Ui.btn(this,"Novo lembrete");rem.setOnClickListener(v->newReminder());actions.addView(cal,new LinearLayout.LayoutParams(0,Ui.dp(this,52),1));actions.addView(rem,new LinearLayout.LayoutParams(0,Ui.dp(this,52),1));root.addView(actions);Ui.gap(this,root,12);TextView h=title("Clientes");h.setTextSize(20);root.addView(h);renderClients();}
 @Override protected void onResume(){super.onResume();ds.load();if(root!=null){root.removeViews(4,root.getChildCount()-4);TextView h=title("Clientes");h.setTextSize(20);root.addView(h);renderClients();updateSummary();}AlarmScheduler.rescheduleAll(this);}
 void updateSummary(){int n=0,over=0;double total=0,paid=0;long now=System.currentTimeMillis();for(Models.Client c:ds.clients)for(Models.Loan l:c.loans){n++;total+=l.total;paid+=l.paid();for(int i=0;i<l.installments;i++)if(!l.installmentPaid(i)&&l.dueAt(i)<now)over++;}summary.setText(String.format(Locale.getDefault(),"Clientes: %d  •  Contratos: %d\nEmprestado: R$ %.2f  •  Recebido: R$ %.2f\nA receber: R$ %.2f  •  Parcelas atrasadas: %d",ds.clients.size(),n,total,paid,Math.max(0,total-paid),over));summary.setTextColor(Color.LTGRAY);}
 void renderClients(){updateSummary();for(Models.Client c:ds.clients){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(Ui.dp(this,12),Ui.dp(this,10),Ui.dp(this,12),Ui.dp(this,10));card.setBackgroundColor(Color.rgb(30,30,30));TextView tv=Ui.text(this,c.name+"\n"+(c.phone.isEmpty()?"":c.phone),17);tv.setOnClickListener(v->{Intent i=new Intent(this,ClientActivity.class);i.putExtra("id",c.id);startActivity(i);});card.addView(tv);double bal=0;for(Models.Loan l:c.loans)bal+=l.balance();TextView b=Ui.text(this,String.format(Locale.getDefault(),"Em aberto: R$ %.2f",bal),14);b.setTextColor(bal>0?gold:Color.rgb(45,190,120));card.addView(b);root.addView(card,new LinearLayout.LayoutParams(-1,Ui.dp(this,82)));Ui.gap(this,root,7);}}
 void newReminder(){LinearLayout p=Ui.col(this);EditText t=Ui.field(this,"Título do lembrete");EditText d=Ui.field(this,"Detalhes (opcional)");p.addView(t);Ui.gap(this,p,8);p.addView(d);new AlertDialog.Builder(this).setTitle("Novo lembrete").setView(p).setPositiveButton("Data e hora",(x,w)->pickDateTime(t.getText().toString(),d.getText().toString())).setNegativeButton("Cancelar",null).show();}
 void pickDateTime(String title,String details){Calendar c=Calendar.getInstance();new DatePickerDialog(this,(v,y,m,day)->{Calendar x=Calendar.getInstance();x.set(y,m,day);new TimePickerDialog(this,(tv,h,min)->{x.set(Calendar.HOUR_OF_DAY,h);x.set(Calendar.MINUTE,min);x.set(Calendar.SECOND,0);Models.Reminder r=new Models.Reminder();r.title=title.isEmpty()?"Lembrete":title;r.details=details;r.when=x.getTimeInMillis();ds.reminders.add(r);ds.save();AlarmScheduler.schedule(this,"reminder",r.id,r.title,r.when);Toast.makeText(this,"Lembrete salvo",Toast.LENGTH_SHORT).show();},Calendar.getInstance().get(Calendar.HOUR_OF_DAY),Calendar.getInstance().get(Calendar.MINUTE),true).show();},c.get(Calendar.YEAR),c.get(Calendar.MONTH),c.get(Calendar.DAY_OF_MONTH)).show();}
}
